{+START,IF_PASSED,TITLE}
	<h2>{TITLE*}</h2>
{+END}

{+START,IF_PASSED,HELP}{+START,IF_NON_EMPTY,{HELP}}
	<div{+START,IF_PASSED,TITLE} id="fes{TITLE|}_help"{+END}>
		{$PARAGRAPH,{HELP*}}
	</div>
{+END}{+END}
